- name: "Install Monitoring"
  hosts: aws_monitor
  vars:
    scylla_servers_yml_path: ./scylla_servers.yml
    scylla_monitoring_dashboards_versions:
      - '2024.1'
    scylla_monitoring_archive_url: 'https://github.com/scylladb/scylla-monitoring/archive/refs/tags/scylla-monitoring-4.6.1.tar.gz'
    alerts_sender_email: example-email@example.com
    alerts_sender_password: Sender_p@ssw0rd
    alerts_receiver_email: example-email@example.com
    scylla_cluster_name: Bench
  roles:
    - ansible-scylla-monitoring

